// <auto-generated />
using System;
using DietApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231025203226_1Mig")]
    partial class _1Mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietApp.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryName = "Et Ürünleri"
                        },
                        new
                        {
                            ID = 2,
                            CategoryName = "Deniz Ürünleri"
                        },
                        new
                        {
                            ID = 3,
                            CategoryName = "Sebzeler"
                        },
                        new
                        {
                            ID = 4,
                            CategoryName = "Meyveler"
                        },
                        new
                        {
                            ID = 5,
                            CategoryName = "Süt ve Süt Ürünleri"
                        },
                        new
                        {
                            ID = 6,
                            CategoryName = "Baklagiller"
                        },
                        new
                        {
                            ID = 7,
                            CategoryName = "Tahıllar ve Ekmekler"
                        },
                        new
                        {
                            ID = 8,
                            CategoryName = "Hamur İşleri"
                        },
                        new
                        {
                            ID = 9,
                            CategoryName = "Atıştırmalıklar"
                        },
                        new
                        {
                            ID = 10,
                            CategoryName = "Tatlılar ve Şekerli Ürünler"
                        },
                        new
                        {
                            ID = 11,
                            CategoryName = "Salatalar"
                        },
                        new
                        {
                            ID = 12,
                            CategoryName = "İçecekler"
                        },
                        new
                        {
                            ID = 13,
                            CategoryName = "Çorba ve Çorba Çeşitleri"
                        },
                        new
                        {
                            ID = 14,
                            CategoryName = "Baharatlar ve Soslar"
                        },
                        new
                        {
                            ID = 15,
                            CategoryName = "Atıştırmalık Yiyecekler"
                        },
                        new
                        {
                            ID = 16,
                            CategoryName = "Diyabetik Ürünler"
                        },
                        new
                        {
                            ID = 17,
                            CategoryName = "Vegan Yiyecekler"
                        },
                        new
                        {
                            ID = 18,
                            CategoryName = "Vejetaryen Yiyecekler"
                        },
                        new
                        {
                            ID = 19,
                            CategoryName = "Glutensiz Ürünler"
                        },
                        new
                        {
                            ID = 20,
                            CategoryName = "Laktosiz Ürünler"
                        },
                        new
                        {
                            ID = 21,
                            CategoryName = "Sağlıklı Yağlar ve Yağlı Yiyecekler"
                        },
                        new
                        {
                            ID = 22,
                            CategoryName = "Dondurulmuş Yiyecekler"
                        },
                        new
                        {
                            ID = 23,
                            CategoryName = "Hazır Yemekler"
                        },
                        new
                        {
                            ID = 24,
                            CategoryName = "Hızlı Yiyecekler"
                        },
                        new
                        {
                            ID = 25,
                            CategoryName = "Sağlıklı Atıştırmalıklar"
                        },
                        new
                        {
                            ID = 26,
                            CategoryName = "Organik Ürünler"
                        },
                        new
                        {
                            ID = 27,
                            CategoryName = "Yoğurt ve Fermente Ürünler"
                        },
                        new
                        {
                            ID = 28,
                            CategoryName = "Kahvaltılıklar"
                        },
                        new
                        {
                            ID = 29,
                            CategoryName = "Kuruyemişler ve Tohumlar"
                        },
                        new
                        {
                            ID = 30,
                            CategoryName = "Diyet İçecekler"
                        });
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.FoodPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FoodPhotos");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.MealType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MealTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            MealName = "Kahvaltı"
                        },
                        new
                        {
                            ID = 2,
                            MealName = "Brunch"
                        },
                        new
                        {
                            ID = 3,
                            MealName = "Öğle Yemeği"
                        },
                        new
                        {
                            ID = 4,
                            MealName = "Çay Vakti"
                        },
                        new
                        {
                            ID = 5,
                            MealName = "Akşam Yemeği"
                        },
                        new
                        {
                            ID = 6,
                            MealName = "Hafif Akşam Yemeği"
                        },
                        new
                        {
                            ID = 7,
                            MealName = "Gece Atıştırmalığı"
                        });
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserDayMealFood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodPhotoID")
                        .HasColumnType("int");

                    b.Property<int>("MealTypeID")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Portion")
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserFoodID")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FoodPhotoID");

                    b.HasIndex("MealTypeID");

                    b.HasIndex("UserFoodID");

                    b.HasIndex("UserID");

                    b.ToTable("UserDayMealFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserFood", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("UserID");

                    b.ToTable("UserFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserDayMealFood", b =>
                {
                    b.HasOne("DietApp.Entities.Concrete.FoodPhoto", "FoodPhoto")
                        .WithMany("UserDayMealFoods")
                        .HasForeignKey("FoodPhotoID");

                    b.HasOne("DietApp.Entities.Concrete.MealType", "MealType")
                        .WithMany("UserDayMealFoods")
                        .HasForeignKey("MealTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietApp.Entities.Concrete.UserFood", "UserFood")
                        .WithMany("UserDayMealFoods")
                        .HasForeignKey("UserFoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietApp.Entities.Concrete.User", null)
                        .WithMany("UserDayMealFoods")
                        .HasForeignKey("UserID");

                    b.Navigation("FoodPhoto");

                    b.Navigation("MealType");

                    b.Navigation("UserFood");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserDetails", b =>
                {
                    b.HasOne("DietApp.Entities.Concrete.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("DietApp.Entities.Concrete.UserDetails", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserFood", b =>
                {
                    b.HasOne("DietApp.Entities.Concrete.Category", "Category")
                        .WithMany("UserFoods")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietApp.Entities.Concrete.User", "User")
                        .WithMany("UserFoods")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.Category", b =>
                {
                    b.Navigation("UserFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.FoodPhoto", b =>
                {
                    b.Navigation("UserDayMealFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.MealType", b =>
                {
                    b.Navigation("UserDayMealFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.User", b =>
                {
                    b.Navigation("UserDayMealFoods");

                    b.Navigation("UserDetails")
                        .IsRequired();

                    b.Navigation("UserFoods");
                });

            modelBuilder.Entity("DietApp.Entities.Concrete.UserFood", b =>
                {
                    b.Navigation("UserDayMealFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
